### ISSUE TITLE
What miui version does the current version support Xiaomi 11? My current device is version 14.0.8miui

### ISSUE THREAD

**Issue by LarissaLycoris** [SnowCore8/xiaomi_sm8350_kernel#2]
What miui version does the current version support Xiaomi 11? My current device is version 14.0.8miui

**Comment by SnowCore8** [comment]
> 当前版本支持小米11什么miui版本？我当前的设备版本是14.0.8miui

基于小米开源判断MIUI12.5.4应该是正常使用的
